name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the stack
      run: |
        cd ci
        docker-compose up -d
  test:
    steps:
    - name: test
      run: echo testdayo
