name: CI

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: action/checkout@v1
    - name: Build the stack
      run: docker-compose up -d
    - name: Test
      run: echo 'hello!'
