name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the stack
      run: docker-compose up -d

    # steps:
    # - uses: action/checkout@v1
    # - name: Build the stack
    #   run: docker-compose up -d
    # - name: Test
    #   run: echo 'hello!'
